name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy pytest

      - name: Lint with flake8
        run: flake8 fsassistant tests

      - name: Check code format with black
        run: black --check fsassistant tests

      - name: Check import order with isort
        run: isort --check-only fsassistant tests

      - name: Static type check with mypy
        run: mypy fsassistant

      - name: Run tests with pytest
        run: pytest tests
