name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort mypy pytest

      - name: Lint with flake8
        run: flake8 fsassistant tests

      - name: Static type check with mypy
        run: mypy fsassistant

      - name: Run tests with pytest
        run: python -m pytest
